version: "3.9"

services:
  vault:
    image: vaultwarden/server:1.24.0
    environment:
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN: "EpRVaPgOtn6O6Q7OkwHFVX/ewUdJ3iQfqKj+5SuIX9qs3M7bAc/VPWRNmqU4otVh"
      DATABASE_URL: "postgresql://vault:vault@db:5432/vault"
    expose:
      - "80"
      - "3012"
    depends_on:
      db:
        condition: service_healthy
      proxy:
        condition: service_started

  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_PASSWORD: "vault"
      POSTGRES_USER: "vault"
      POSTGRES_DB: "vault"
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vault"]

  proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ./certs:/certs
      - ./.data/caddy/data:/data
      - ./.data/caddy/config:/config
